### ISSUE TITLE
[Bug] Conversion not possible

### ISSUE THREAD

**Issue by KASMaxMueller** [PSAppDeployToolkit/PSAppDeployToolkit.Tools#3]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit.tools/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit.tools/releases/latest)

### PSAppDeployToolkit.Tools version

0.0.21

### PSAppDeployToolkit version

3.10.2

### Describe the bug

PS C:\Install> Test-ADTCompatibility

cmdlet Test-ADTCompatibility at command pipeline position 1
Supply values for the following parameters:
FilePath: C:\Install\Deploy-Application.ps1
WARNING: A command that prompts the user failed because the host program or the command type does not support user
interaction. The host was attempting to request confirmation with the following message: The Update-Help cmdlet
downloads the most current Help files for Windows PowerShell modules, and installs them on your computer. For more
information about the Update-Help cmdlet, see https:/go.microsoft.com/fwlink/?LinkId=210614.
Test-ADTCompatibility : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Test-ADTCompatibility
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Windo....ScriptAnalyzer:ScriptAnalyzer) [Test-ADTCompatibility]
   , CmdletInvocationException
    + FullyQualifiedErrorId : 80131501,Test-ADTCompatibility

### Steps to reproduce

1.using a current deploy-application.ps1 file from our template
2. run command Test-ADTCompatibility and choose file

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile


Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by DanGough** [comment]
I've never tested it interactively like that, but it's working for me:
![image](https://github.com/user-attachments/assets/1f7df3ff-a7bf-40e8-877b-7f53f16a677d)

As for this:

> WARNING: A command that prompts the user failed because the host program or the command type does not support user interaction.

Are you just running in a regular PowerShell console or Windows Terminal? If not, give that a go, or just supply `-FilePath` on the command line.

I'll close this for now, but please comment back if you are unable to get this to work with the advice above.
